version: '3.8'

services:
    # Redis 
    redis:
        image: redis
        command: redis-server --requirepass ${REDIS_PASSWORD} --bind redis
        ports:
            - "6379:6379"
        networks:
            - goldmund-network
    # Data Processing Service
    goldmund-api:
        container_name: goldmund-api
        restart: always
        build: 
            context: packages/goldmund-api
            dockerfile: Dockerfile.dev
        command: npm run dev
        env_file: 
            - .env
        volumes:
            - ./packages/goldmund-api:/home/node/app
            - api_node_modules:/home/node/app/node_modules
            - logs:/home/node/app/logs
        networks:
            - goldmund-network
        depends_on:
            - redis
    # SSR 'client' app
    goldmund-client:
        container_name: goldmund-client
        build:
            context: packages/goldmund-client
            dockerfile: Dockerfile.dev
        command: /bin/bash -c "./wait-for-it.sh goldmund-api:5000 --timeout=60 -- npm run build && npm run start"
        environment:
            - API_BASE_DOCKER=http://goldmund-api:5000
            - API_BASE_CLIENT=/api/
        volumes:
            - ./packages/goldmund-client:/home/node/app
            - client_node_modules:/home/node/app/node_modules
            - client_dist:/home/node/app/.next
        networks:
            - goldmund-network
        depends_on:
            - goldmund-api
            - redis
    nginx: 
        restart: always
        build: 
            context: packages/goldmund-server
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - goldmund-network
        depends_on:
            - goldmund-client
        
networks:
    goldmund-network:
        driver: bridge

volumes:
    api_node_modules: 
    logs:
    client_node_modules:
    client_dist:
    