version: '3.8'

services:
    # Redis 
    redis:
        image: redis
        command: redis-server --requirepass ${REDIS_PASSWORD} --bind redis
        ports:
            - "6379:6379"
        networks:
            - goldmundio
    # Data Processing Service
    goldmund-api:
        container_name: goldmund-api
        image: exbotanical/goldmundio:api-${TAG}
        command: npm start #TODO replace w/manager
        env_file: 
            - .env
        networks:
            - goldmundio
        depends_on:
            - redis
    # SSR 'client' app
    goldmund-client:
        image: exbotanical/goldmundio:client-${TAG}
        container_name: goldmund-client
        command: /bin/bash -c "./wait-for-it.sh goldmund-api:5000 --timeout=60 -- npm run build && npm run start"
        environment:
            - API_BASE_DOCKER=https://goldmund-api:5000
            - API_BASE_CLIENT=https://goldmund.io:5000
        networks:
            - goldmundio
        depends_on:
            - goldmund-api
            - redis
    nginx: 
        restart: always
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - goldmundio
        depends_on:
            - goldmund-client
networks:
    goldmundio:
        driver: bridge
