version: '3.8'

services:
    # Redis 
    redis:
        image: redis
        command: redis-server --requirepass ${REDIS_PASSWORD} --bind redis
        ports:
            - "6379:6379"
        networks:
            - goldmundio
    # Data Processing Service
    goldmund-api:
        container_name: goldmund-api
        restart: always
        build: 
            context: packages/dps-api
            dockerfile: Dockerfile
        command: npm run dev # npm start prod
        working_dir: /usr/src/dps-api
        env_file: 
            - .env
        volumes: 
            - ./packages/dps-api:/usr/src/dps-api
        ports:
            - "5000:5000"
        networks:
            - goldmundio
        depends_on:
            - redis
    # SSR 'client' app
    nextjs:
        container_name: goldmund-client
        build:
            context: packages/next-server
            dockerfile: Dockerfile
        command: npm start
        env_file:
            - .env
        volumes:
            - ./packages/next-server:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/.next
        ports:
            - "3000:3000"
        networks:
            - goldmundio
networks:
    goldmundio:
        driver: bridge