apiVersion: apps/v1
kind: Deployment
metadata:
    name: goldmund-client-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: web
    template:
        metadata:
            labels:
                component: web
        spec:
            containers: 
                - name: goldmund-client
                  image: exbotanical/goldmund-client
                  env:
                    - name: API_BASE_DOCKER
                      value: https://goldmund-api-service:5000
                    - name: API_BASE_CLIENT
                      value: /api
                    - name: NEXT_TELEMETRY_DISABLED
                      value: "1"
                  ports:
                    - containerPort: 3000
